---
version: '2'
services:
    react:
        image: zachhamilton/jackpot-frontend
        hostname: react
        container_name: react
        ports: 
            - 80:80
    express:
        image: zachhamilton/jackpot-backend
        hostname: express
        container_name: express
        ports:
            - 8080:8080
        environment:
            BOOTSTRAP_SERVERS: "<bootstrap-servers>"
            SASL_USERNAME: "<api-key>"
            SASL_PASSWORD: "<api-secret>"
            SASL_MECHANISM: PLAIN
            SECURITY_PROTOCOL: SASL_SSL
            KSQLDB_USERNAME: "<ksqldb-api-key>"
            KSQLDB_PASSWORD: "<ksqldb-api-secret>"
            KSQLDB_ENDPOINT: "<ksqldb-endpoint>"     
      